### ISSUE TITLE
clear backup folder inside the container to keep storage in check

### ISSUE THREAD

**Issue by vijayabharathib** [tamil-wiki/mediawiki-backup-restore#17]
backup cron is running in a container and sending files to s3. all files are deleted after pushing to s3. however, some files stayed within the container , using 25GB of data. 

this has to be debugged and fixed.

**Comment by arulrajnet** [comment]
The root cause of the issue is, when the backup failed we didn't clear the tar file inside the /backup directory. 

![2022-11-02_12-29](https://user-images.githubusercontent.com/834529/199423600-c48d7f32-62c0-478a-8092-a97249a5e61d.png)

Failed log

![2022-11-02_12-41](https://user-images.githubusercontent.com/834529/199423642-ee8372b6-e72c-4ce9-a948-d716780e9728.png)

Will fix the same.
